### ISSUE TITLE
Hovering over profile picture in chat inverts/messes up colors on profile picture.

### ISSUE THREAD

**Issue by EmeraldImpulse7** [Saltssaumure/pios-discord-theme#22]
Self explanatory.

Without hovering:
![image](https://user-images.githubusercontent.com/61766021/185697293-e27255fd-d799-4ec9-8321-e81967070e52.png)

With hovering:
![image](https://user-images.githubusercontent.com/61766021/185697372-23f95685-62fc-4d94-9799-7594828f1480.png)

This does not happen on the user list sidebar, only in chat. It does not happen to server icons either.
I know piOS Forever is the cause, as I disabled all other themes.

**Comment by Saltssaumure** [comment]
Ahhh this is deliberate - originally added it for only the Clyde/SYSTEM messages, then added it for all chat icons.
It can be disabled by turning on Reduced Motion mode (accessibility settings), or by using the following in Custom CSS:
```css
.full-motion :not(.ephemeral-2nDdnn)>.contents-2MsGLg>.avatar-2e8lTP.clickable-31pE3P:hover {
    filter: none;
}
```
