### ISSUE TITLE
Glowing effect

### ISSUE THREAD

**Issue by LucidNyxx** [Saltssaumure/pios-discord-theme#6]
Is there a way to remove the glowing effect on the text and everything?
Also, I did install RadialStatus, but nothing happened. It still looks the same.

Thanks!

**Comment by Saltssaumure** [comment]
Sure thing. Copy paste this into the Custom CSS editor and save. If it doesn't work and you already have other things in the editor, let me know.

```css
/* Removes text glow from piOS Forever theme */
:root {
    --mainGlowColor: transparent!important;
    --mutedGlowColor: transparent!important;
    --SHTeamGlowColor: transparent!important;
    --SHMindsGlowColor: transparent!important;
}
span {
    text-shadow: none!important;
}
/* End remove text glow section */
```
